DROP USER MAIL CASCADE;

CREATE USER MAIL IDENTIFIED BY mailpass;

ALTER USER MAIL DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

ALTER USER MAIL TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO MAIL;

GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO MAIL;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO MAIL;